### ISSUE TITLE
bittrex.websockets.listen.example.js timing

### ISSUE THREAD

**Issue by Janti87** [n0mad01/node.bittrex.api#27]
How to run below each 0.3-0.5 second but same time to get all pairs. 

```javascript
t bittrex = require('../node.bittrex.api');

const websocketsclient = bittrex.websockets.listen ( function( data ) {
  if (data.M === 'updateSummaryState') {
    data.A.forEach(function(data_for) {
      data_for.Deltas.forEach(function(marketsDelta)  { 
        console.log('Ticker Update for '+ marketsDelta.MarketName, marketsDelta);
      });
    });
  }
});
```

**Comment by n0mad01** [comment]
i don't understand what you are trying to do.

websockets is a  full duplex message based communication protocol which means that you receive data whenever it gets "pushed" by bittrex.

you could make use of the standard requests but i would not recommend to request too often, otherwise you'll get banned.

see https://bitcoin.stackexchange.com/a/55163/31585

**Comment by Janti87** [comment]
See, I know when some pumps will happen, so I need this code to work within milliseconds, within 2-3 seconds pump is becoming dump, will not work

What do you think about this?

**Comment by n0mad01** [comment]
i still have no idea which usecases you are adressing, so i can't help you with that.

regarding latency you should contact bittrex.
